
  void main() {
print("Q.4");
print("Answer\n");


int temp = 42;

if(temp<0)
{
  print("Freezing weather");
}
else if (temp>=0 && temp < 10)
{
  print("very cold weather");
}
else if (temp>=10 && temp < 20)
{
  print("its cold weather");
}else if (temp>=20 && temp < 30)
{
  print("this is normal temperature");
}else if (temp>=30 && temp < 40)
{
  print("its hot weather");
}else if (temp>=40)
{
  print("its very hot weather");
}


  }

